### ISSUE TITLE
Change in color for nav bar

### ISSUE THREAD

**Issue by Pragya-Manandhar** [Pragya-Manandhar/collaboration#2]
The color of all the hyperlinks and the color of the logo does not go well with each other. Make sure the hyperlinks have the same color as that of the logo.  #74c043 this is the hexadecimal number needed.

**Comment by pritsma** [comment]
i edited and check it now

**Comment by pritsma** [comment]
![image](https://user-images.githubusercontent.com/81896281/118373657-c30df500-b5d7-11eb-9830-6557a101eb7c.png)
code by pragya
